all_words = [{'name': 'car', 'hint': 'Thing'}, 
             {'name': 'turtle', 'hint': 'Animal'}, 
             {'name': 'london', 'hint': 'City'},
             {'name': 'penguin', 'hint': 'Animal'},
             {'name': 'apple', 'hint': 'Fruit'},
             {'name': 'switzerland', 'hint': 'Country'},
             {'name': 'tokyo', 'hint': 'City'},
             {'name': 'paris', 'hint': 'City'},
             {'name': 'pear', 'hint': 'Fruit'},
             {'name': 'avocado', 'hint': 'Fruit'},
             {'name': 'calculator', 'hint': 'Thing'},
             {'name': 'france', 'hint': 'Country'},
             {'name': 'rabbit', 'hint': 'Animal'},
             {'name': 'phone', 'hint': 'Thing'},
             ]
